# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/sensor_msgs/NavSatStatus.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ros/sensor_msgs/NavSatStatus.proto',
  package='ros.sensor_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\"ros/sensor_msgs/NavSatStatus.proto\x12\x0fros.sensor_msgs\"/\n\x0cNavSatStatus\x12\x0e\n\x06status\x18\x01 \x01(\x11\x12\x0f\n\x07service\x18\x02 \x01(\x05\x62\x06proto3'
)




_NAVSATSTATUS = _descriptor.Descriptor(
  name='NavSatStatus',
  full_name='ros.sensor_msgs.NavSatStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ros.sensor_msgs.NavSatStatus.status', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='ros.sensor_msgs.NavSatStatus.service', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['NavSatStatus'] = _NAVSATSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NavSatStatus = _reflection.GeneratedProtocolMessageType('NavSatStatus', (_message.Message,), {
  'DESCRIPTOR' : _NAVSATSTATUS,
  '__module__' : 'ros.sensor_msgs.NavSatStatus_pb2'
  # @@protoc_insertion_point(class_scope:ros.sensor_msgs.NavSatStatus)
  })
_sym_db.RegisterMessage(NavSatStatus)


# @@protoc_insertion_point(module_scope)
