# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorNearData/PowerTrain.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
from SensorNearData import SensorStates_pb2 as SensorNearData_dot_SensorStates__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SensorNearData/PowerTrain.proto',
  package='pb.SensorNearData',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1fSensorNearData/PowerTrain.proto\x12\x11pb.SensorNearData\x1a\x0cheader.proto\x1a!SensorNearData/SensorStates.proto\"\x8e\x04\n\nPowerTrain\x12\x1a\n\x06header\x18\x01 \x01(\x0b\x32\n.pb.Header\x12\x30\n\x04\x65rrs\x18\x03 \x01(\x0b\x32\".pb.SensorNearData.PowerTrain.Errs\x12\x36\n\x07signals\x18\x04 \x01(\x0b\x32%.pb.SensorNearData.PowerTrain.Signals\x1ai\n\x04\x45rrs\x12+\n\x04gear\x18\x01 \x01(\x0e\x32\x10.pb.SensorStates:\x0bSTATE_FAULT\x12\x34\n\rgas_pedal_pos\x18\x02 \x01(\x0e\x32\x10.pb.SensorStates:\x0bSTATE_FAULT\x1a]\n\x07Signals\x12\x18\n\rgas_pedal_pos\x18\x03 \x01(\x02:\x01\x30\x12\x38\n\x04gear\x18\x07 \x01(\x0e\x32\".pb.SensorNearData.PowerTrain.Gear:\x06GEAR_N\"\xaf\x01\n\x04Gear\x12\n\n\x06GEAR_N\x10\x00\x12\n\n\x06GEAR_R\x10\x01\x12\n\n\x06GEAR_P\x10\x02\x12\n\n\x06GEAR_D\x10\x03\x12\x0b\n\x07GEAR_D1\x10\x04\x12\x0b\n\x07GEAR_D2\x10\x05\x12\x0b\n\x07GEAR_D3\x10\x06\x12\x0b\n\x07GEAR_D4\x10\x07\x12\x0b\n\x07GEAR_D5\x10\x08\x12\x0b\n\x07GEAR_D6\x10\t\x12\x0b\n\x07GEAR_D7\x10\n\x12\x0c\n\x08GEAR_SNA\x10\x0b\x12\x0e\n\nGEAR_UNDEF\x10\x0c'
  ,
  dependencies=[header__pb2.DESCRIPTOR,SensorNearData_dot_SensorStates__pb2.DESCRIPTOR,])



_POWERTRAIN_GEAR = _descriptor.EnumDescriptor(
  name='Gear',
  full_name='pb.SensorNearData.PowerTrain.Gear',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GEAR_N', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEAR_R', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEAR_P', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEAR_D', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEAR_D1', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEAR_D2', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEAR_D3', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEAR_D4', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEAR_D5', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEAR_D6', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEAR_D7', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEAR_SNA', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEAR_UNDEF', index=12, number=12,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=455,
  serialized_end=630,
)
_sym_db.RegisterEnumDescriptor(_POWERTRAIN_GEAR)


_POWERTRAIN_ERRS = _descriptor.Descriptor(
  name='Errs',
  full_name='pb.SensorNearData.PowerTrain.Errs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gear', full_name='pb.SensorNearData.PowerTrain.Errs.gear', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gas_pedal_pos', full_name='pb.SensorNearData.PowerTrain.Errs.gas_pedal_pos', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=357,
)

_POWERTRAIN_SIGNALS = _descriptor.Descriptor(
  name='Signals',
  full_name='pb.SensorNearData.PowerTrain.Signals',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gas_pedal_pos', full_name='pb.SensorNearData.PowerTrain.Signals.gas_pedal_pos', index=0,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gear', full_name='pb.SensorNearData.PowerTrain.Signals.gear', index=1,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=452,
)

_POWERTRAIN = _descriptor.Descriptor(
  name='PowerTrain',
  full_name='pb.SensorNearData.PowerTrain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='pb.SensorNearData.PowerTrain.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errs', full_name='pb.SensorNearData.PowerTrain.errs', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signals', full_name='pb.SensorNearData.PowerTrain.signals', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_POWERTRAIN_ERRS, _POWERTRAIN_SIGNALS, ],
  enum_types=[
    _POWERTRAIN_GEAR,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=630,
)

_POWERTRAIN_ERRS.fields_by_name['gear'].enum_type = SensorNearData_dot_SensorStates__pb2._SENSORSTATES
_POWERTRAIN_ERRS.fields_by_name['gas_pedal_pos'].enum_type = SensorNearData_dot_SensorStates__pb2._SENSORSTATES
_POWERTRAIN_ERRS.containing_type = _POWERTRAIN
_POWERTRAIN_SIGNALS.fields_by_name['gear'].enum_type = _POWERTRAIN_GEAR
_POWERTRAIN_SIGNALS.containing_type = _POWERTRAIN
_POWERTRAIN.fields_by_name['header'].message_type = header__pb2._HEADER
_POWERTRAIN.fields_by_name['errs'].message_type = _POWERTRAIN_ERRS
_POWERTRAIN.fields_by_name['signals'].message_type = _POWERTRAIN_SIGNALS
_POWERTRAIN_GEAR.containing_type = _POWERTRAIN
DESCRIPTOR.message_types_by_name['PowerTrain'] = _POWERTRAIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PowerTrain = _reflection.GeneratedProtocolMessageType('PowerTrain', (_message.Message,), {

  'Errs' : _reflection.GeneratedProtocolMessageType('Errs', (_message.Message,), {
    'DESCRIPTOR' : _POWERTRAIN_ERRS,
    '__module__' : 'SensorNearData.PowerTrain_pb2'
    # @@protoc_insertion_point(class_scope:pb.SensorNearData.PowerTrain.Errs)
    })
  ,

  'Signals' : _reflection.GeneratedProtocolMessageType('Signals', (_message.Message,), {
    'DESCRIPTOR' : _POWERTRAIN_SIGNALS,
    '__module__' : 'SensorNearData.PowerTrain_pb2'
    # @@protoc_insertion_point(class_scope:pb.SensorNearData.PowerTrain.Signals)
    })
  ,
  'DESCRIPTOR' : _POWERTRAIN,
  '__module__' : 'SensorNearData.PowerTrain_pb2'
  # @@protoc_insertion_point(class_scope:pb.SensorNearData.PowerTrain)
  })
_sym_db.RegisterMessage(PowerTrain)
_sym_db.RegisterMessage(PowerTrain.Errs)
_sym_db.RegisterMessage(PowerTrain.Signals)


# @@protoc_insertion_point(module_scope)
