# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorNearData/VehicleDynamics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
from SensorNearData import SensorStates_pb2 as SensorNearData_dot_SensorStates__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SensorNearData/VehicleDynamics.proto',
  package='pb.SensorNearData',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n$SensorNearData/VehicleDynamics.proto\x12\x11pb.SensorNearData\x1a\x0cheader.proto\x1a!SensorNearData/SensorStates.proto\"\xa2\x08\n\x0fVehicleDynamics\x12\x1a\n\x06header\x18\x01 \x01(\x0b\x32\n.pb.Header\x12\x35\n\x04\x65rrs\x18\x03 \x01(\x0b\x32\'.pb.SensorNearData.VehicleDynamics.Errs\x12;\n\x07signals\x18\x04 \x01(\x0b\x32*.pb.SensorNearData.VehicleDynamics.Signals\x12@\n\ntimestamps\x18\x07 \x01(\x0b\x32,.pb.SensorNearData.VehicleDynamics.Timestamp\x1a\xac\x03\n\x04\x45rrs\x12,\n\x05speed\x18\x01 \x01(\x0e\x32\x10.pb.SensorStates:\x0bSTATE_FAULT\x12\x36\n\x0fspeed_displayed\x18\x02 \x01(\x0e\x32\x10.pb.SensorStates:\x0bSTATE_FAULT\x12-\n\x0fspeed_per_wheel\x18\x03 \x03(\x0e\x32\x10.pb.SensorStatesB\x02\x10\x01\x12/\n\x08long_acc\x18\x04 \x01(\x0e\x32\x10.pb.SensorStates:\x0bSTATE_FAULT\x12.\n\x07lat_acc\x18\x05 \x01(\x0e\x32\x10.pb.SensorStates:\x0bSTATE_FAULT\x12.\n\x07yawrate\x18\x06 \x01(\x0e\x32\x10.pb.SensorStates:\x0bSTATE_FAULT\x12;\n\x14steering_wheel_angle\x18\x07 \x01(\x0e\x32\x10.pb.SensorStates:\x0bSTATE_FAULT\x12\x41\n\x1asteering_wheel_angle_speed\x18\x08 \x01(\x0e\x32\x10.pb.SensorStates:\x0bSTATE_FAULT\x1a\xc4\x01\n\x07Signals\x12\r\n\x05speed\x18\x01 \x01(\x02\x12\x17\n\x0fspeed_displayed\x18\x02 \x01(\x02\x12\x1b\n\x0fspeed_per_wheel\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\x10\n\x08long_acc\x18\x04 \x01(\x02\x12\x0f\n\x07lat_acc\x18\x05 \x01(\x02\x12\x0f\n\x07yawrate\x18\x06 \x01(\x02\x12\x1c\n\x14steering_wheel_angle\x18\x07 \x01(\x02\x12\"\n\x1asteering_wheel_angle_speed\x18\x08 \x01(\x02\x1a\xc6\x01\n\tTimestamp\x12\r\n\x05speed\x18\x01 \x01(\x12\x12\x17\n\x0fspeed_displayed\x18\x02 \x01(\x12\x12\x1b\n\x0fspeed_per_wheel\x18\x03 \x03(\x12\x42\x02\x10\x01\x12\x10\n\x08long_acc\x18\x04 \x01(\x12\x12\x0f\n\x07lat_acc\x18\x05 \x01(\x12\x12\x0f\n\x07yawrate\x18\x06 \x01(\x12\x12\x1c\n\x14steering_wheel_angle\x18\x07 \x01(\x12\x12\"\n\x1asteering_wheel_angle_speed\x18\x08 \x01(\x12'
  ,
  dependencies=[header__pb2.DESCRIPTOR,SensorNearData_dot_SensorStates__pb2.DESCRIPTOR,])




_VEHICLEDYNAMICS_ERRS = _descriptor.Descriptor(
  name='Errs',
  full_name='pb.SensorNearData.VehicleDynamics.Errs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='pb.SensorNearData.VehicleDynamics.Errs.speed', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed_displayed', full_name='pb.SensorNearData.VehicleDynamics.Errs.speed_displayed', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed_per_wheel', full_name='pb.SensorNearData.VehicleDynamics.Errs.speed_per_wheel', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long_acc', full_name='pb.SensorNearData.VehicleDynamics.Errs.long_acc', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat_acc', full_name='pb.SensorNearData.VehicleDynamics.Errs.lat_acc', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yawrate', full_name='pb.SensorNearData.VehicleDynamics.Errs.yawrate', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steering_wheel_angle', full_name='pb.SensorNearData.VehicleDynamics.Errs.steering_wheel_angle', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steering_wheel_angle_speed', full_name='pb.SensorNearData.VehicleDynamics.Errs.steering_wheel_angle_speed', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=767,
)

_VEHICLEDYNAMICS_SIGNALS = _descriptor.Descriptor(
  name='Signals',
  full_name='pb.SensorNearData.VehicleDynamics.Signals',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='pb.SensorNearData.VehicleDynamics.Signals.speed', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed_displayed', full_name='pb.SensorNearData.VehicleDynamics.Signals.speed_displayed', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed_per_wheel', full_name='pb.SensorNearData.VehicleDynamics.Signals.speed_per_wheel', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long_acc', full_name='pb.SensorNearData.VehicleDynamics.Signals.long_acc', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat_acc', full_name='pb.SensorNearData.VehicleDynamics.Signals.lat_acc', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yawrate', full_name='pb.SensorNearData.VehicleDynamics.Signals.yawrate', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steering_wheel_angle', full_name='pb.SensorNearData.VehicleDynamics.Signals.steering_wheel_angle', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steering_wheel_angle_speed', full_name='pb.SensorNearData.VehicleDynamics.Signals.steering_wheel_angle_speed', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=770,
  serialized_end=966,
)

_VEHICLEDYNAMICS_TIMESTAMP = _descriptor.Descriptor(
  name='Timestamp',
  full_name='pb.SensorNearData.VehicleDynamics.Timestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='pb.SensorNearData.VehicleDynamics.Timestamp.speed', index=0,
      number=1, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed_displayed', full_name='pb.SensorNearData.VehicleDynamics.Timestamp.speed_displayed', index=1,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed_per_wheel', full_name='pb.SensorNearData.VehicleDynamics.Timestamp.speed_per_wheel', index=2,
      number=3, type=18, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long_acc', full_name='pb.SensorNearData.VehicleDynamics.Timestamp.long_acc', index=3,
      number=4, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat_acc', full_name='pb.SensorNearData.VehicleDynamics.Timestamp.lat_acc', index=4,
      number=5, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yawrate', full_name='pb.SensorNearData.VehicleDynamics.Timestamp.yawrate', index=5,
      number=6, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steering_wheel_angle', full_name='pb.SensorNearData.VehicleDynamics.Timestamp.steering_wheel_angle', index=6,
      number=7, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steering_wheel_angle_speed', full_name='pb.SensorNearData.VehicleDynamics.Timestamp.steering_wheel_angle_speed', index=7,
      number=8, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=969,
  serialized_end=1167,
)

_VEHICLEDYNAMICS = _descriptor.Descriptor(
  name='VehicleDynamics',
  full_name='pb.SensorNearData.VehicleDynamics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='pb.SensorNearData.VehicleDynamics.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errs', full_name='pb.SensorNearData.VehicleDynamics.errs', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signals', full_name='pb.SensorNearData.VehicleDynamics.signals', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamps', full_name='pb.SensorNearData.VehicleDynamics.timestamps', index=3,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_VEHICLEDYNAMICS_ERRS, _VEHICLEDYNAMICS_SIGNALS, _VEHICLEDYNAMICS_TIMESTAMP, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=1167,
)

_VEHICLEDYNAMICS_ERRS.fields_by_name['speed'].enum_type = SensorNearData_dot_SensorStates__pb2._SENSORSTATES
_VEHICLEDYNAMICS_ERRS.fields_by_name['speed_displayed'].enum_type = SensorNearData_dot_SensorStates__pb2._SENSORSTATES
_VEHICLEDYNAMICS_ERRS.fields_by_name['speed_per_wheel'].enum_type = SensorNearData_dot_SensorStates__pb2._SENSORSTATES
_VEHICLEDYNAMICS_ERRS.fields_by_name['long_acc'].enum_type = SensorNearData_dot_SensorStates__pb2._SENSORSTATES
_VEHICLEDYNAMICS_ERRS.fields_by_name['lat_acc'].enum_type = SensorNearData_dot_SensorStates__pb2._SENSORSTATES
_VEHICLEDYNAMICS_ERRS.fields_by_name['yawrate'].enum_type = SensorNearData_dot_SensorStates__pb2._SENSORSTATES
_VEHICLEDYNAMICS_ERRS.fields_by_name['steering_wheel_angle'].enum_type = SensorNearData_dot_SensorStates__pb2._SENSORSTATES
_VEHICLEDYNAMICS_ERRS.fields_by_name['steering_wheel_angle_speed'].enum_type = SensorNearData_dot_SensorStates__pb2._SENSORSTATES
_VEHICLEDYNAMICS_ERRS.containing_type = _VEHICLEDYNAMICS
_VEHICLEDYNAMICS_SIGNALS.containing_type = _VEHICLEDYNAMICS
_VEHICLEDYNAMICS_TIMESTAMP.containing_type = _VEHICLEDYNAMICS
_VEHICLEDYNAMICS.fields_by_name['header'].message_type = header__pb2._HEADER
_VEHICLEDYNAMICS.fields_by_name['errs'].message_type = _VEHICLEDYNAMICS_ERRS
_VEHICLEDYNAMICS.fields_by_name['signals'].message_type = _VEHICLEDYNAMICS_SIGNALS
_VEHICLEDYNAMICS.fields_by_name['timestamps'].message_type = _VEHICLEDYNAMICS_TIMESTAMP
DESCRIPTOR.message_types_by_name['VehicleDynamics'] = _VEHICLEDYNAMICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VehicleDynamics = _reflection.GeneratedProtocolMessageType('VehicleDynamics', (_message.Message,), {

  'Errs' : _reflection.GeneratedProtocolMessageType('Errs', (_message.Message,), {
    'DESCRIPTOR' : _VEHICLEDYNAMICS_ERRS,
    '__module__' : 'SensorNearData.VehicleDynamics_pb2'
    # @@protoc_insertion_point(class_scope:pb.SensorNearData.VehicleDynamics.Errs)
    })
  ,

  'Signals' : _reflection.GeneratedProtocolMessageType('Signals', (_message.Message,), {
    'DESCRIPTOR' : _VEHICLEDYNAMICS_SIGNALS,
    '__module__' : 'SensorNearData.VehicleDynamics_pb2'
    # @@protoc_insertion_point(class_scope:pb.SensorNearData.VehicleDynamics.Signals)
    })
  ,

  'Timestamp' : _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), {
    'DESCRIPTOR' : _VEHICLEDYNAMICS_TIMESTAMP,
    '__module__' : 'SensorNearData.VehicleDynamics_pb2'
    # @@protoc_insertion_point(class_scope:pb.SensorNearData.VehicleDynamics.Timestamp)
    })
  ,
  'DESCRIPTOR' : _VEHICLEDYNAMICS,
  '__module__' : 'SensorNearData.VehicleDynamics_pb2'
  # @@protoc_insertion_point(class_scope:pb.SensorNearData.VehicleDynamics)
  })
_sym_db.RegisterMessage(VehicleDynamics)
_sym_db.RegisterMessage(VehicleDynamics.Errs)
_sym_db.RegisterMessage(VehicleDynamics.Signals)
_sym_db.RegisterMessage(VehicleDynamics.Timestamp)


_VEHICLEDYNAMICS_ERRS.fields_by_name['speed_per_wheel']._options = None
_VEHICLEDYNAMICS_SIGNALS.fields_by_name['speed_per_wheel']._options = None
_VEHICLEDYNAMICS_TIMESTAMP.fields_by_name['speed_per_wheel']._options = None
# @@protoc_insertion_point(module_scope)
